version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - im_haruto_web_node_modules:/app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development

volumes:
  im_haruto_web_node_modules: